### ISSUE TITLE
Enrich issues with GitHub Issue Events information

### ISSUE THREAD

**Issue by tdakanalis** [cytechmobile/radicle-github-migrate#15]
A lot of information about a GitHub issue is captured as an [Issue Event](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28). We will extend the tooling so we can extract these events into the Radicle Issues we create. 

_In the case where the Radicle Issue doesn’t allow storing this information in its own model, we will create a comments with this information, so the information is not lost, and we will also open a feature request for the Heartwood team to consider extending the model accordingly._

**Comment by gsaslis** [comment]
How's this list for a start?

- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#assigned
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#closed
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#commented
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#connected
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#cross-referenced
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#demilestoned
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#disconnected
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#labeled
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#mentioned
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#milestoned
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#referenced
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#renamed
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#reopened
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#unassigned
- https://docs.github.com/en/webhooks-and-events/events/issue-event-types#unlabeled

**Comment by tdakanalis** [comment]
Good starting point! Some comments below:

- **commented**: this event appears to be redundant because events are migrated as comments within a Radicle issue (as Radicle currently does not support events).
- **connected**, **disconnected**: although these events are useful, the GitHub API does not provide a correlation between the event and the respective Pull Request or Issue. This limitation reduces the overall usefulness of the event.

**Comment by gsaslis** [comment]
ok, let's exclude those 2 to begin with ;)
